### ISSUE TITLE
Remove the asynchronous_command_bus alias

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/AsynchronousBundle#2]
I think we should remove the `asynchronous_command_bus` alias because now it's a public service which you could acces and when you use it to send a message through this bus it is handled in sync and not async. You need to send it to the `command_bus` service because that is sending it async when no other handler is found.

**Comment by matthiasnoback** [comment]
Interesting! I'll see if we can change without any grave consequences :)
Op 18 apr. 2015 14:34 schreef "Cliff Odijk" <notifications@github.com>:

**Comment by cmodijk** [comment]
Tested but it's needed for the test suit i'm not going to change this.
