### ISSUE TITLE
Cache:clear command throws InvalidArgumentException after updating to Symfony 3.2

### ISSUE THREAD

**Issue by Davidmattei** [SimpleBus/AsynchronousBundle#9]
Hello, 

I'm having a problem after updating to **Symfony 3.2**. When I run the cache:clear or cache:warmup command our application throws a InvailidArgumentException 'The class or interface "services" does not exist'. 

I think it's related to this new feature : [https://github.com/symfony/symfony/pull/19507](https://github.com/symfony/symfony/pull/19507)

This new cache warmer receives the AsynchronousBundle **serialization.yml** and failed to get metadata for it.

```
php bin/console cache:warmup -vvv

 // Warming up the cache for the dev environment with debug true



  [Symfony\Component\Serializer\Exception\InvalidArgumentException]
  The class or interface "services" does not exist.
```

Greetings

David

**Comment by cmodijk** [comment]
@Davidmattei thanks for taking the time sumbit this pull request. But i'm not able to reproduce this error which serializer did you implement or use? I'm using the `SimpleBus\Serialization\ObjectSerializer` and that seems fine. Could you provider steps te reproduce or a sample project so i could check this out and test it?

**Comment by Davidmattei** [comment]
@cmodijk just found the mistake after creating a blank new Symfony project with the following bundles installed : 

new JMS\SerializerBundle\JMSSerializerBundle(),
new SimpleBus\AsynchronousBundle\SimpleBusAsynchronousBundle(),
new SimpleBus\JMSSerializerBundleBridge\SimpleBusJMSSerializerBundleBridgeBundle()

This works fine, but in our project we also enabled the serializer option for the frameworkBundle.

**app/config.yml**
framework:
    serializer:      ~

 I think this creates a conflict ?

**Comment by cmodijk** [comment]
@Davidmattei thanks for checking i will try to test that tomorrow

**Comment by cmodijk** [comment]
So symfony reads the `[serialization.yml](https://github.com/SimpleBus/AsynchronousBundle/blob/master/src/Resources/config/serialization.yml)` and thinks that is configuration for there serialzer i find that strange is there any documentation at the Symfony that defines they `Resources/config/serialization.yml` path as a configuration file for there serialzer? I'm looking for it but can't find it.

**Comment by cmodijk** [comment]
I have a fix ready only problem is that travis is failing i'm first have to fix that before i'm able to merge it and make a new release for you.

**Comment by Davidmattei** [comment]
@cmodijk thanks for the quick and good support !

**Comment by cmodijk** [comment]
@Davidmattei No problem i just tagged the 2.3.0 version with the fix
